# Import libraries

In [22]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

# Load data

In [23]:
data = pd.read_csv('b5.csv')

In [24]:
data.head()

,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,...,O1,O2,O3,O4,O5,O6,O7,O8,O9,O10
0,4,2,5,2,5,1,4,3,5,1,...,4,1,3,1,5,1,4,2,5,5
1,2,2,3,3,3,3,1,5,1,5,...,3,3,3,3,2,3,3,1,3,2
2,5,1,1,4,5,1,1,5,5,1,...,4,5,5,1,5,1,5,5,5,5
3,2,5,2,4,3,4,3,4,4,5,...,4,3,5,2,4,2,5,2,5,5
4,3,1,3,3,3,1,3,1,3,5,...,3,1,1,1,3,1,3,1,5,3

In [25]:
data.describe()

,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,...,O1,O2,O3,O4,O5,O6,O7,O8,O9,O10
count,18930.000000,18930.000000,18930.00000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,...,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000,18930.000000
mean,2.630375,2.759113,3.41775,3.151981,3.433228,2.450819,2.869995,3.376440,3.092446,3.585156,...,3.695985,2.146804,4.127787,2.074908,3.872055,1.794506,4.075225,3.211939,4.135394,4.006075
std,1.231010,1.312125,1.23533,1.221943,1.281626,1.240543,1.430686,1.265017,1.395642,1.302745,...,1.114061,1.132116,1.006658,1.107746,0.940687,1.068241,0.920613,1.256600,0.980554,0.984166
min,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,3.00000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,3.000000,...,3.000000,1.000000,4.000000,1.000000,3.000000,1.000000,4.000000,2.000000,4.000000,3.000000
50%,3.000000,3.000000,4.00000,3.000000,4.000000,2.000000,3.000000,3.000000,3.000000,4.000000,...,4.000000,2.000000,4.000000,2.000000,4.000000,1.000000,4.000000,3.000000,4.000000,4.000000
75%,4.000000,4.000000,4.00000,4.000000,5.000000,3.000000,4.000000,4.000000,4.000000,5.000000,...,5.000000,3.000000,5.000000,3.000000,5.000000,2.000000,5.000000,4.000000,5.000000,5.000000
max,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [20]:
#convert the data to a numpy array
X = data.values

In [26]:
X

array([[4, 2, 5, ..., 2, 5, 5],
       [2, 2, 3, ..., 1, 3, 2],
       [5, 1, 1, ..., 5, 5, 5],
       ...,
       [2, 5, 4, ..., 5, 5, 5],
       [1, 4, 2, ..., 3, 5, 5],
       [2, 3, 1, ..., 5, 5, 5]], dtype=int64)

## Scale the values

In [28]:
#scale the values so that all the variables are in the same range 
#(and so that one variable doesn't overwhelm the others)
X = scale(X)

C:\Users\brent\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)

In [29]:
X

array([[ 1.112632  , -0.57855181,  1.28086553, ..., -0.96448433,
         0.88177594,  1.0099427 ],
       [-0.51209309, -0.57855181, -0.33817724, ..., -1.76030372,
        -1.15794039, -2.03840414],
       [ 1.92499454, -1.34069418, -1.95722   , ...,  1.42297383,
         0.88177594,  1.0099427 ],
       ...,
       [-0.51209309,  1.70787529,  0.47134415, ...,  1.42297383,
         0.88177594,  1.0099427 ],
       [-1.32445564,  0.94573292, -1.14769862, ..., -0.16866494,
         0.88177594,  1.0099427 ],
       [-0.51209309,  0.18359055, -1.95722   , ...,  1.42297383,
         0.88177594,  1.0099427 ]])

# Conduct PCA
## PCA with 50 components

In [30]:
#Do the actual PCA analysis, with 50 components, since we have 50 variables. 
#This shows how much of the total variance each one of these components explains
#Starts with 1 and goes to 40
#The first accounts for 16.1 percent of the variance, the second accounts for 9.2 percent, etc.
pca = PCA()
pca.fit(X)
print(pca.explained_variance_ratio_)

[ 0.16101911  0.09246263  0.07527279  0.07100381  0.05526279  0.0313044
  0.02660753  0.02099101  0.01937029  0.01849593  0.01794133  0.01735232
  0.01689316  0.01604282  0.01576013  0.01470117  0.01459846  0.01438242
  0.01362569  0.01322527  0.0131285   0.01268631  0.01223362  0.01180048
  0.01164071  0.01136677  0.01108761  0.0106515   0.01045028  0.0102118
  0.01003675  0.00983507  0.00974897  0.00963948  0.0089566   0.00894
  0.00868373  0.00840808  0.00831106  0.00808253  0.00793945  0.00760062
  0.00748126  0.00727417  0.00694749  0.00689884  0.00650197  0.00647554
  0.0062404   0.00442735]

## PCA with 5 components

In [33]:
#since there are supposedly 5 "personality factors" the data should reflect a 5-component solution
#so we will do PCA for 5 components
pca5 = PCA(n_components=5)
pca5.fit(X)
print(pca5.explained_variance_ratio_)

[ 0.16101911  0.09246261  0.07527276  0.07100371  0.0552626 ]

## Contributions of variables to components

In [35]:
#so for each of the 50 variables, we see how much each variable contributes to each of the components, 
print(pca5.components_)

[[-0.18390787  0.17969715 -0.25064919  0.20613652 -0.23167014  0.19768209
  -0.22070035  0.13297407 -0.16463324  0.20183673  0.15466094 -0.12978555
   0.1227194  -0.10236699  0.14227196  0.16681188  0.16277779  0.17394502
   0.17756804  0.19476253  0.09256156 -0.1776637   0.09908268 -0.11467442
   0.13341572 -0.05636296  0.18786032 -0.1328581  -0.11973055 -0.18783752
  -0.11091541  0.05023858 -0.07324394  0.15189963 -0.10873762  0.09267625
  -0.04455739  0.13905485 -0.09130734 -0.09522267 -0.06943355  0.09889371
  -0.03539302  0.07185541 -0.1305411   0.08698216 -0.11181738 -0.01241611
   0.00436469 -0.11687499]
 [-0.12861676  0.16739084 -0.07307813  0.09545647 -0.14848476  0.12805806
  -0.13659411  0.10836266 -0.11569746  0.07579782 -0.22729884  0.14372646
  -0.21602033  0.11918885 -0.18825448 -0.25218545 -0.24451971 -0.24840617
  -0.19625149 -0.18518083  0.08482718 -0.17629219 -0.05191838 -0.19237067
   0.17356926 -0.17862971  0.17027956 -0.1403114  -0.20736933 -0.09459585
   0.12416478 -0.16244966  0.04196064 -0.20157144  0.11322804 -0.16954897
   0.07224177 -0.11058429  0.07159866  0.05409127 -0.01408439 -0.02886255
  -0.10901265  0.02691311 -0.02195119  0.06269967  0.03791996 -0.04570292
  -0.08995684 -0.06995396]
 [ 0.15468192 -0.14202239  0.06434705 -0.16683257  0.08702486 -0.1032889
   0.12547566 -0.19084417  0.17681044 -0.15792223 -0.12679384  0.10493867
  -0.18023085  0.05551443 -0.03555332 -0.08461758 -0.00681933 -0.00972905
  -0.02360283 -0.06607271  0.14082548 -0.07858694  0.20502667 -0.24970651
   0.17245978 -0.22640104  0.11282164 -0.18883809 -0.2232159  -0.07491966
  -0.18955707  0.18296788 -0.182432    0.1480034  -0.20997723  0.18973528
  -0.22810101  0.18087506 -0.24096723 -0.17502397  0.03025288 -0.03906302
   0.0243349  -0.01213991  0.03020627 -0.03342897 -0.01388209  0.06319731
  -0.12655366  0.04911286]
 [ 0.06434984 -0.07063387  0.113772   -0.0879013   0.06365984  0.03443773
   0.0831362  -0.04996208  0.01030752 -0.0769961  -0.00723057  0.01082844
  -0.03034733  0.06481248  0.03452918  0.0049616  -0.04200832 -0.03810375
  -0.04659629 -0.08903673 -0.00524389  0.05269403 -0.0849072   0.06929443
  -0.07289135  0.09203144 -0.08039894  0.05119801  0.04021288  0.03248734
  -0.08173879 -0.03832461 -0.1665949  -0.01432355  0.03795148 -0.01480974
  -0.05520094  0.00607241  0.00373399 -0.14327472 -0.32941967  0.29342027
  -0.29007029  0.25276539 -0.29762328  0.25778486 -0.26763215 -0.325288
  -0.20944517 -0.33009352]
 [ 0.15035239 -0.12984851  0.06707791 -0.1359469   0.13066801 -0.07219758
   0.12685235 -0.14178883  0.15536615 -0.11109328  0.14196196 -0.14671287
   0.10435569  0.00089123  0.12071443  0.15353083  0.16191079  0.16610753
   0.22676414  0.05031339  0.17825988 -0.10961922  0.16667192 -0.20734481
   0.19374181 -0.14183498  0.15450996 -0.14068831 -0.14277271 -0.02297261
   0.21231094 -0.19862402  0.11489976 -0.11681315  0.23616095 -0.19498135
   0.22225999 -0.09047278  0.24838288  0.16691211 -0.01913007  0.11519505
  -0.05560477  0.15303967  0.06790057  0.0702251   0.02646311  0.00132554
  -0.06747395  0.00853553]]